name: webServerWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2
        run: |
          echo "${{secrets.KEY_EC2}}" > private_key && chmod 400 private_key
             ssh -o StrictHostKeyChecking=no -i private_key ec2-54-175-64-253.compute-1.amazonaws.com "
                 cd /var/www/html/index.html &&
                 sudo git pull "
